# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: "최차장의 퇴근 후 다이어리"
# subtitle: "건담조아"
#email: blcentra@gmail.com
name: "최차장"
# description: >
#  연남동 최차장입니다.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/choichajang" # the subpath of your site, e.g. /blog/
url: "http://choichajang.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: choichajang

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# comment
facebook_app_id: 378872509298788

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@Thechoichajang"             # (User) Name to display in the footer link
#     url: https://twitter.com/Thechoichajang # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username: choichajang
    url: "https://web.facebook.com/ChoiChaJang"
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: choichajang
    url: https://github.com/choichajang
    desc: Fork me on GitHub
    share: true

 # - name: LinkedIn
 #   icon: linkedin
 #   username: Ben Centra
 #   url: https://www.linkedin.com/pub/ben-centra/47/769/60a
 #   desc: Connect with me on LinkedIn
 #   share: true

#  - name: Google+
#    icon: google-plus
#    username:
#    url:
#    desc: Add me to your Circles
#    share: true

#  - name: YouTube
#    icon: youtube
#    username:
#    url:
#    desc: Subscribe on YouTube
#    share: false

#  - name: Instagram
#    icon: instagram
#    username:
#    url:
#    desc: Follow me on Instagram
#    share: false



# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    os_repo: "https://github.com/choichajang/"
    os_rcs_type: "git"
    os_src: "https://github.com/choichajang/"
